// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwpGMM7m4o0g7tdK8o7Nj5WRvfNxv8FQ',
    appId: '1:221407104091:web:7e3a21932830e49cbac37e',
    messagingSenderId: '221407104091',
    projectId: 'fruit-hub-1ac54',
    authDomain: 'fruit-hub-1ac54.firebaseapp.com',
    storageBucket: 'fruit-hub-1ac54.firebasestorage.app',
    measurementId: 'G-XS0K6F9957',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXVjE992nyy5WS_QY2StJE99XVO0nA40',
    appId: '1:221407104091:android:50b816bae74d44cebac37e',
    messagingSenderId: '221407104091',
    projectId: 'fruit-hub-1ac54',
    storageBucket: 'fruit-hub-1ac54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV60fSQBLNbS6hCAQMYNK4SETBT9O_IFE',
    appId: '1:221407104091:ios:f30ae4b32e083e0cbac37e',
    messagingSenderId: '221407104091',
    projectId: 'fruit-hub-1ac54',
    storageBucket: 'fruit-hub-1ac54.firebasestorage.app',
    iosBundleId: 'com.example.realECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV60fSQBLNbS6hCAQMYNK4SETBT9O_IFE',
    appId: '1:221407104091:ios:f30ae4b32e083e0cbac37e',
    messagingSenderId: '221407104091',
    projectId: 'fruit-hub-1ac54',
    storageBucket: 'fruit-hub-1ac54.firebasestorage.app',
    iosBundleId: 'com.example.realECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSwpGMM7m4o0g7tdK8o7Nj5WRvfNxv8FQ',
    appId: '1:221407104091:web:6252a078df71fed8bac37e',
    messagingSenderId: '221407104091',
    projectId: 'fruit-hub-1ac54',
    authDomain: 'fruit-hub-1ac54.firebaseapp.com',
    storageBucket: 'fruit-hub-1ac54.firebasestorage.app',
    measurementId: 'G-HV9KLECSCV',
  );
}
